name: Release CLI

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    env:
      DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      SERVICE_URL: ${{ secrets.AUTH0_SERVICE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout 5m

      - name: Install GitHub CLI
        uses: cli/cli-action@v2

      - name: Auth GH CLI using PAT
        run: echo "${{ secrets.RELEASE_GH_TOKEN }}" | gh auth login --with-token

      - name: Build and Release
        run: |
          make release \
            DOMAIN="${DOMAIN}" \
            CLIENT_ID="${CLIENT_ID}" \
            AUDIENCE="${AUDIENCE}" \
            SERVICE_URL="${SERVICE_URL}"
