name: Release Drafter

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release draft (optional)'
        required: false
        type: string

permissions:
  contents: read

jobs:
  create_release_draft:
    name: Create Release Draft
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Create release draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          disable-autolabeler: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
