// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gateway_stream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GatewayMessage represents a message sent between the Optimum Gateway and clients.
type GatewayMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	MessageId     string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_gateway_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_gateway_stream_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GatewayMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *GatewayMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GatewayMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GatewayMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_gateway_stream_proto protoreflect.FileDescriptor

const file_gateway_stream_proto_rawDesc = "" +
	"\n" +
	"\x14gateway_stream.proto\x12\x05proto\"\x90\x01\n" +
	"\x0eGatewayMessage\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type2Q\n" +
	"\rGatewayStream\x12@\n" +
	"\fClientStream\x12\x15.proto.GatewayMessage\x1a\x15.proto.GatewayMessage(\x010\x01B\x18Z\x16mump2p-cli/proto;protob\x06proto3"

var (
	file_gateway_stream_proto_rawDescOnce sync.Once
	file_gateway_stream_proto_rawDescData []byte
)

func file_gateway_stream_proto_rawDescGZIP() []byte {
	file_gateway_stream_proto_rawDescOnce.Do(func() {
		file_gateway_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_stream_proto_rawDesc), len(file_gateway_stream_proto_rawDesc)))
	})
	return file_gateway_stream_proto_rawDescData
}

var file_gateway_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gateway_stream_proto_goTypes = []any{
	(*GatewayMessage)(nil), // 0: proto.GatewayMessage
}
var file_gateway_stream_proto_depIdxs = []int32{
	0, // 0: proto.GatewayStream.ClientStream:input_type -> proto.GatewayMessage
	0, // 1: proto.GatewayStream.ClientStream:output_type -> proto.GatewayMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_stream_proto_init() }
func file_gateway_stream_proto_init() {
	if File_gateway_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_stream_proto_rawDesc), len(file_gateway_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_stream_proto_goTypes,
		DependencyIndexes: file_gateway_stream_proto_depIdxs,
		MessageInfos:      file_gateway_stream_proto_msgTypes,
	}.Build()
	File_gateway_stream_proto = out.File
	file_gateway_stream_proto_goTypes = nil
	file_gateway_stream_proto_depIdxs = nil
}
